### ISSUE TITLE
Not able to run the linux version on fedora, undefined symbol related to some python lib Qt_5

### ISSUE THREAD

**Issue by marouamghar** [kubernetes-sigs/minikube-gui#49]
I downloaded the tar and ran it on fedora, but i get this error:
`./minikube-gui: symbol lookup error: ./minikube-gui: undefined symbol: _ZdlPvm, version Qt_5`

**Comment by afbjorklund** [comment]
It is not python, it is a C++ symbol.

```console
$ c++filt _ZdlPvm
operator delete(void*, unsigned long)
```

Probably related to some library version mismatch, you might have to recompile it yourself

**Comment by mickdelaney** [comment]
+ 1 for me on ubuntu

Description:	Ubuntu 22.04.3 LTS
Release:	22.04

`/usr/local/bin/minikube-gui: symbol lookup error: /usr/local/bin/minikube-gui: undefined symbol: _ZdlPvm, version Qt_5
`

**Comment by afbjorklund** [comment]
I think the linux download will need to bundle the needed libraries, as for other platforms.

**Comment by afbjorklund** [comment]
Please try the AppImage from the PR, see if that works better:

https://github.com/kubernetes-sigs/minikube-gui/actions/runs/6159526894?pr=95

> Artifacts
>
> [minikube-gui-linux](https://github.com/kubernetes-sigs/minikube-gui/suites/16078786189/artifacts/926930174)

**Comment by afbjorklund** [comment]
On Ubuntu, you can install the [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) debian package from PPA, for a better user experience:

![AppImageLauncherUbuntu](https://github.com/kubernetes-sigs/minikube-gui/assets/10364051/60975447-47ca-40c0-a2b8-3b7e3d882aca)

It will integrate the application with the desktop, so that it can be double-clicked and appear in the menus.

![AppImageLauncherApplications](https://github.com/kubernetes-sigs/minikube-gui/assets/10364051/2eb90ac9-c840-4588-aced-60f7d6a05f81)
